dist: trusty
sudo: require

language: cpp
compiler: gcc

addons:
  apt:
    packages:
      - cmake-data
      - cmake
      - libboost-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
